using System;
using System.Collections.Generic;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Text;

namespace POE_PROG6212
{
    public partial class ViewClaims : Page
    {
        // Sample claims data
        private static List<ClaimRecord> claims;

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                LoadClaims();
            }
        }

        private void LoadClaims()
        {
            claims = new List<ClaimRecord>
            {
                new ClaimRecord { ClaimId = 1, LecturerName = "Siyanqoba", DateOfWork = "01/09/2024", HoursWorked = 5, HourlyRate = 50, TotalAmount = 250, Status = "Pending" },
                new ClaimRecord { ClaimId = 2, LecturerName = "Asanda", DateOfWork = "02/09/2024", HoursWorked = 8, HourlyRate = 60, TotalAmount = 480, Status = "Pending" },
                new ClaimRecord { ClaimId = 3, LecturerName = "Landile", DateOfWork = "03/09/2024", HoursWorked = 7, HourlyRate = 55, TotalAmount = 385, Status = "Pending" },
                new ClaimRecord { ClaimId = 4, LecturerName = "Wandile", DateOfWork = "04/09/2024", HoursWorked = 6, HourlyRate = 52, TotalAmount = 312, Status = "Pending" }
            };

            ClaimsGridView.DataSource = claims;
            ClaimsGridView.DataBind();
        }

        protected void DownloadInvoiceButton_Click(object sender, EventArgs e)
        {
            // Assuming the claim ID to generate the invoice
            int claimId = 1; // Replace with dynamic selection logic if needed

            var claim = claims.Find(c => c.ClaimId == claimId);
            if (claim != null)
            {
                StringBuilder invoiceHtml = new StringBuilder();

                invoiceHtml.Append("<html><body>");
                invoiceHtml.Append("<h2>Invoice for Claim ID: " + claim.ClaimId + "</h2>");
                invoiceHtml.Append("<table border='1' cellpadding='5' cellspacing='0'>");
                invoiceHtml.Append("<tr><th>Lecturer Name</th><td>" + claim.LecturerName + "</td></tr>");
                invoiceHtml.Append("<tr><th>Date of Work</th><td>" + claim.DateOfWork + "</td></tr>");
                invoiceHtml.Append("<tr><th>Hours Worked</th><td>" + claim.HoursWorked + "</td></tr>");
                invoiceHtml.Append("<tr><th>Hourly Rate</th><td>" + claim.HourlyRate + "</td></tr>");
                invoiceHtml.Append("<tr><th>Total Amount</th><td>" + claim.TotalAmount + "</td></tr>");
                invoiceHtml.Append("</table>");
                invoiceHtml.Append("<br /><br />");
                invoiceHtml.Append("<footer><p>Generated by HR System</p></footer>");
                invoiceHtml.Append("</body></html>");

                string fileName = "Invoice_Claim_" + claim.ClaimId + ".html";
                Response.Clear();
                Response.ContentType = "text/html";
                Response.AddHeader("Content-Disposition", "attachment;filename=" + fileName);
                Response.Write(invoiceHtml.ToString());
                Response.End();
            }
            else
            {
                ScriptManager.RegisterStartupScript(this, GetType(), "NoClaim", "alert('Claim not found.');", true);
            }
        }
    }

    // ClaimRecord class to represent the claim data
    public class ClaimRecord
    {
        public int ClaimId { get; set; }
        public string LecturerName { get; set; }
        public string DateOfWork { get; set; }
        public double HoursWorked { get; set; }
        public double HourlyRate { get; set; }
        public double TotalAmount { get; set; }
        public string Status { get; set; }
    }
}
